In [1]:
#NumPy is a Python fundamental package used for efficient manipulations and operations on High-level mathematical functions, Multi-dimensional arrays, Linear algebra, Fourier Transformations, Random Number Capabilities, etc. It provides tools for integrating C, C++, and Fortran code in Python. NumPy is mostly used in Python for scientific computing. 

In [18]:
# importing required packages
import numpy
import time

# size of arrays and lists
size = 1000000   

# declaring lists
list1 = range(size)
list2 = range(size)

# declaring arrays
array1 = numpy.arange(size)  
array2 = numpy.arange(size)

# list
initialTime = time.time()
resultantList = [(a * b) for a, b in zip(list1, list2)]

# calculating execution time
print("Time taken by Lists :", 
      (time.time() - initialTime),
      "seconds")

# NumPy array
initialTime = time.time()
resultantArray = array1 * array2

# calculating execution time 
print("Time taken by NumPy Arrays :",
      (time.time() - initialTime),
      "seconds")

#numpy computational speed is faster than lists

Time taken by Lists : 0.313490629196167 seconds
Time taken by NumPy Arrays : 0.011546611785888672 seconds


In [19]:
#Arrays in Numpy
#Array in Numpy is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In Numpy, number of dimensions of the array is called rank of the array. A tuple of integers giving the size of the array along each dimension is known as shape of the array. An array class in Numpy is called as ndarray. Elements in Numpy arrays are accessed by using square brackets and can be initialized by using nested Python Lists.

In [25]:
#Creating a Numpy Array
import numpy as np
#creating rank1 array

array1=np.array([1,2,3])
print("using rank 1 array",array1)

#creating rank 2 array
array2=np.array([[1,2,3],[4,5,6]])
print("\n using rank 2 array",array2)

#creating using tuple
array3 = np.array((1,2,3))
print("using tuple",array3)

using rank 1 array [1 2 3]

 using rank 2 array [[1 2 3]
 [4 5 6]]
using tuple [1 2 3]


In [43]:
#accessing the array index
#slicing - using slicing we can access index

array1=np.array([[1,2,3,4],[2,3,4,5],[5,6,7,8],[-1,-2,-3,-4]])
print(array1)
print("\n")

#print first row 
#print(array1[0,:])

#Get the second column
print(array1[:,2])

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 5  6  7  8]
 [-1 -2 -3 -4]]


[ 3  4  7 -3]


In [48]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Slicing a subarray
# Get a 2x2 subarray
sub_matrix = matrix[0:2,1:3]
print(sub_matrix)

[[2 3]
 [5 6]]


In [49]:
#numpy.array - we covered above
#numpy.zeroes()
import numpy as np

# Creating a 2D array with 3 rows and 4 columns
arr = np.zeros((3, 4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [62]:
#np.ones():
# Python Program illustrating
# numpy.ones method

import numpy as np

b = np.ones(2)


print("\n",b)

a = np.ones([2, 2] , dtype=int)
print("\n",a)

c = np.ones([3, 3],dtype=int)
print(c)


 [1. 1.]

 [[1 1]
 [1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [63]:
#np.arange()
a=np.arange(20)

In [64]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [65]:
b=np.arange(2,20)

In [66]:
print(b)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [67]:
c=np.arange(2,20,3) #prints from 2 to 20 by stepping 3 like 2, 2+3 , +3 , till 20 and skips 20
print(c)

[ 2  5  8 11 14 17]


In [68]:
sequence = np.arange(0, 1, 0.2)
print("Floating-Point Sequence:", sequence)

Floating-Point Sequence: [0.  0.2 0.4 0.6 0.8]


In [69]:
import numpy as np 

# Creating a sequence of numbers from 0 to 20 
a = np.arange(0, 20, 3)

# Filtering the sequence to include only values greater than 10
filtered = a[a > 10]
print("Filtered array:", filtered)

Filtered array: [12 15 18]


In [3]:
#np.linspace() linspace() function in NumPy returns an array of evenly spaced numbers over a specified range. Unlike the range() function in Python that generates numbers with a specific step size. linspace() allows you to specify the total number of points you want in the array, and NumPy will calculate the spacing between the numbers automatically.
import numpy as np

# Generate 10 numbers between 0 and 1
array1 = np.linspace(0, 1, num=10) # this prints 10 numbers between 0 and 1
array2 = np.linspace(0, 1, num=30) # this prints 30 numbers from 0 to 1 evenly spaced
print(array1)
print(array2)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[0.         0.03448276 0.06896552 0.10344828 0.13793103 0.17241379
 0.20689655 0.24137931 0.27586207 0.31034483 0.34482759 0.37931034
 0.4137931  0.44827586 0.48275862 0.51724138 0.55172414 0.5862069
 0.62068966 0.65517241 0.68965517 0.72413793 0.75862069 0.79310345
 0.82758621 0.86206897 0.89655172 0.93103448 0.96551724 1.        ]


In [4]:
# Array Operations


In [5]:
#reshape
array1 = np.arange(3) #arange() basically gives 1D array
print(array1)

array2 = np.arange(12).reshape(3,4) # it arranges array as multi dimensional using reshape() here 2D
print(array2)

array3 = np.arange(24).reshape(2,3,4) # here 3D
print(array3)

[0 1 2]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [6]:
array2.size # it returns size of the array means how many elements are present in the array

12

In [7]:
print(array2)
print(array2.shape) #.shape returns shape of an array if 3 roes, 4 columns, then (3,4) it returns..

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [9]:
#ndim
array2.ndim # ndim returns the dimension of the array , if 2D , returns 2 , if 3D, it returns 3

2

In [10]:
#The flatten() function is used to convert a multi-dimensional NumPy array into a one-dimensional array. It creates a new copy of the data so that original array stays unchanged. If your array has rows and columns or even more dimensions, then flatten() line up every single value into a straight list, one after another

In [14]:
print("before:",array2)
print("after")
array2.flatten()

before: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
after


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
# how to flatten two 2D NumPy arrays and then concatenate them into a single 1D array using the concatenate() function from NumPy.

In [19]:
print(array2)
print(array2)

a=array2.flatten()
b=array2.flatten()

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  2  4  6  8 10 12 14 16 18 20 22]


In [20]:
# Element-wise operations: +, -, *, /

In [21]:
print(a-b)

[0 0 0 0 0 0 0 0 0 0 0 0]


In [22]:
print(a*b)

[  0   1   4   9  16  25  36  49  64  81 100 121]


In [24]:
print(a**b)

[         1          1          4         27        256       3125
      46656     823543   16777216  387420489 1410065408 1843829075]


In [30]:
#universal functions

In [31]:
print(array2)
a=np.mean(array2) #mean gives mean value of all the elements in array
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
5.5


In [32]:
a=np.sum(array2) # sum() returns sum of all the elements in an array
print(a)

66


In [34]:
a=np.log(array2) # log
print(a)

[[      -inf 0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947 1.94591015]
 [2.07944154 2.19722458 2.30258509 2.39789527]]


C:\Users\Prathyusha Imandi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


In [35]:
a=np.sqrt(array2)
print(a)

[[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479]]


In [36]:
a=np.exp(array2) #exponential of array
print(a)

[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]]


In [37]:
a=np.max(array2) #gives maximum number in an array
print(a)

11


In [38]:
a=np.std(array2) #standard deviation
print(a)

3.452052529534663


In [39]:
a=np.min(array2) #minimum number in an array
print(a)

0


In [41]:
import numpy as np

random_array = np.random.rand(2, 3) #Creates an array of specified shape and fills it with random values sampled from a uniform distribution over [0, 1).
normal_array = np.random.randn(2, 2) #Creates an array of specified shape and fills it with random values sampled from a standard normal distribution
randint_array = np.random.randint(1, 10, size=(2, 3))  #Creates an array of specified shape and fills it with random integers within a given range.

print(random_array)
print(normal_array)
print(randint_array)

[[0.58018738 0.00906083 0.53679462]
 [0.75366602 0.16669351 0.47619146]]
[[ 1.3286626   0.06537758]
 [ 0.15297833 -1.51926124]]
[[4 6 7]
 [9 9 9]]


In [42]:
#np.eye() creates identity matrix
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [43]:
import numpy as np

identity_matrix = np.eye(3)
diagonal_array = np.diag([1, 2, 3])
zeros_like_array = np.zeros_like(diagonal_array)
ones_like_array = np.ones_like(diagonal_array)

print(identity_matrix)
print(diagonal_array)
print(zeros_like_array)
print(ones_like_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [47]:
#Convert list of temperatures in °C to °F
c=[1,2,3,4]
F=[i*33.8 for i in c]
print(F)


[33.8, 67.6, 101.39999999999999, 135.2]


In [56]:
#Find all even numbers in a NumPy array
random_array = np.random.randint(2,30,size=(3,3))
print(random_array)

print(random_array[random_array%2==0])

[[17 29  8]
 [ 7  6 21]
 [ 3 13  2]]
[8 6 2]


In [61]:
#Create a 3×3 matrix with values from 1 to 9 and reshape to 1D
a=np.random.randint(1,9,size=(3,3))
print(a)

b=a.flatten()
print(b)

[[1 7 4]
 [3 8 4]
 [4 7 2]]
[1 7 4 3 8 4 4 7 2]


In [70]:
#Simulate rolling 2 dice 10 times
r=np.random.randint(1,6,size=(1,2))
print(r)

[[5 4]]


In [2]:

import numpy as np

print("=== np.full ===")
a_full = np.full((3, 4), 7)   # 3x4 array filled with 7
print(a_full, "\n")

print("=== ravel() vs flatten() ===")
b = np.array([[1,2,3],[4,5,6]])
print("original shape:", b.shape)
print("flatten():", b.flatten(), "type:", type(b.flatten()))
print("ravel():", b.ravel(), "type:", type(b.ravel()))
# modify ravel view to show difference (ravel may be view, flatten is copy)
r = b.ravel()
r[0] = 99
print("after modifying ravel view, original b[0,0]:", b[0,0])
b = np.array([[1,2,3],[4,5,6]])  # reset
f = b.flatten()
f[0] = 100
print("after modifying flatten copy, original b[0,0]:", b[0,0], "\n")

print("=== np.var (variance) and other aggregations ===")
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("sum:", np.sum(arr), "mean:", np.mean(arr), "var:", np.var(arr), "std:", np.std(arr), "\n")

print("=== np.random.choice (sampling) ===")
np.random.seed(0)
pool = np.array([10,20,30,40,50])
samples = np.random.choice(pool, size=5, replace=True, p=[0.1,0.2,0.3,0.2,0.2])
print("samples:", samples, "\n")

print("=== Broadcasting example ===")
A = np.array([[1],[2],[3]])   # shape (3,1)
B = np.array([10,20,30])      # shape (3,)
# A + B will broadcast B across columns, result shape (3,3)
print("A:\n", A)
print("B:\n", B)
print("A + B:\n", A + B, "\n")

print("=== np.where usage (conditional replace) ===")
x = np.array([1, 6, 3, 9, 2, 8])
y = np.where(x > 5, x, 0)   # replace values <=5 with 0
print("x:", x)
print("where(x>5, x, 0):", y, "\n")

print("=== np.random functions quick demo ===")
print("rand:", np.random.rand(3))
print("randn:", np.random.randn(3))
print("randint 0..9:", np.random.randint(0,10, size=5))


=== np.full ===
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]] 

=== ravel() vs flatten() ===
original shape: (2, 3)
flatten(): [1 2 3 4 5 6] type: <class 'numpy.ndarray'>
ravel(): [1 2 3 4 5 6] type: <class 'numpy.ndarray'>
after modifying ravel view, original b[0,0]: 99
after modifying flatten copy, original b[0,0]: 1 

=== np.var (variance) and other aggregations ===
sum: 55 mean: 5.5 var: 8.25 std: 2.8722813232690143 

=== np.random.choice (sampling) ===
samples: [30 40 40 30 30] 

=== Broadcasting example ===
A:
 [[1]
 [2]
 [3]]
B:
 [10 20 30]
A + B:
 [[11 21 31]
 [12 22 32]
 [13 23 33]] 

=== np.where usage (conditional replace) ===
x: [1 6 3 9 2 8]
where(x>5, x, 0): [0 6 0 9 0 8] 

=== np.random functions quick demo ===
rand: [0.64589411 0.43758721 0.891773  ]
randn: [-0.10321885  0.4105985   0.14404357]
randint 0..9: [8 1 5 9 8]
